config/routes.rb
Rails.application.routes.draw do
  root   'top_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,100}+\z/
  validates :password, presence: true, length: { minimum: 8 },
            format: { with: VALID_PASSWORD_REGEX }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash.now[:danger] = "メールアドレスもしくはパスワードが違います。"
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.now[:success] = "アカウント登録が完了しました。"
      redirect_to @user
    else
      render "new"
    end
  end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title
    if @title.present?
      @title + " | " + "Mymemo"
    else
      "Mymemo"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-deafult navbar-invarse">
  <div class="topbar">
    <%= link_to "Mymemo", root_path, class: "logo-mark" %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "トップ", root_path %></li>
      <% if logged_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          アカウント <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "プロフィール", current_user %></li>
          <li><%= link_to "設定", "#" %></li>
          <li class="divider"></li>
          <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "ログイン", login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shims.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title %></title>
    <%= render "layouts/shims" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/top_pages/home.html.erb
<h1>welcome to mymemo</h1>
<p>自分の予定や気になる事をチェックしよう</p>
<%= link_to "アカウント登録", new_user_path %>
<%= link_to "ログイン", login_path %>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains<%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/new.html.erb
<% @title = "アカウント登録" %>
<h1>アカウント登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render "error_messages" %>
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: "form_control" %>

    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: "form_control" %>

    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: "form_control" %>

    <%= f.label :password_confirmation, "パスワード(確認)" %>
    <%= f.password_field :password_confirmation, class: "form_control" %>

    <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% @title = "ユーザー" %>
<h1>ユーザーページ</h1>